### PR TITLE
chore: minor patches

### PR DESCRIPTION
**Pull request by onbjerg**
- Fixes the GHA badge
- Sets `FOUNDRY_PROFILE` for the entire workflow (allows configuring snapshot too)
- Matches the pragma to what `forge init` creates
- Makes tests pass

### CODE REVIEW

**Comment by mds1** [comment]
Maybe a separate issue, but could also add `forge build --sizes` to CI, ideally as a separate job so a contract exceeding the size limit doesn't block you from know if tests fail

**Comment by onbjerg** [comment]
I wanted to push a patch for that but it seems I do not have push rights to the repository anymore :sweat_smile:

**Comment by mds1** [comment]
Wait sorry, which repo do you not have push rights to?

**Comment by onbjerg** [comment]
> Wait sorry, which repo do you not have push rights to?

This repository

**Pull request merged**
